"""Shared by the System 1 / distill tests: the tiny laya fixture, base checkpoints and run dirs.

The fixture (``tests/fixtures/system1``) is generated by ``tools/system1/make_fixture.py``
from laya 0.3.20 itself: a 2-layer ModernBERT student exported to ONNX, its word-level
tokenizer, and golden answers laya's torch Agent gave on it.
"""

from __future__ import annotations

import json
import shutil
from collections.abc import Mapping
from pathlib import Path
from typing import Any, Final

from aiagent.system1.contract import (
    SUMS_FILE,
    file_sha256,
    format_sha256sums,
    parse_sha256sums,
)

FIXTURE: Final[Path] = Path(__file__).resolve().parent / "fixtures" / "system1"
FIXTURE_MAX_LEN: Final = 128
FIXTURE_HEAD_MAX_LEN: Final = 96

# The artifact files a devai run ships (§3.5); provenance.json is the fixture's own.
ARTIFACT_FILES: Final = (
    "model.onnx",
    "model.onnx.data",
    "rl_agent_config.json",
    "tokenizer/tokenizer.json",
    "tokenizer/tokenizer_config.json",
    "golden.jsonl",
)
MANIFEST: Final = "manifest.json"
JOB_CREATED_AT: Final = 1_790_000_000


def golden_rows() -> list[dict[str, Any]]:
    """The fixture's golden.jsonl rows."""
    lines = (FIXTURE / "golden.jsonl").read_text(encoding="utf-8").splitlines()
    return [json.loads(line) for line in lines if line.strip()]


def make_base_checkpoint(distill_dir: Path, base: str = "laya-multilingual@0000test") -> Path:
    """base/<base>/ with the fixture tokenizer/ and rl_agent_config.json plus a placeholder
    model.safetensors."""
    path = distill_dir / "base" / base
    shutil.copytree(FIXTURE / "tokenizer", path / "tokenizer")
    shutil.copyfile(FIXTURE / "rl_agent_config.json", path / "rl_agent_config.json")
    (path / "model.safetensors").write_bytes(b"placeholder: the tests never load these weights\n")
    return path


def _write_json(path: Path, data: object) -> None:
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def _job(
    job_id: str, *, status: str, model_id: str, training_file: str, artifact_id: str
) -> dict[str, Any]:
    terminal = status in ("succeeded", "failed", "cancelled")
    return {
        "object": "fine_tuning.job",
        "id": job_id,
        "model": model_id,
        "created_at": JOB_CREATED_AT,
        "finished_at": JOB_CREATED_AT + 600 if terminal else None,
        "fine_tuned_model": f"{model_id}:{artifact_id}" if status == "succeeded" else None,
        "status": status,
        "training_file": training_file,
        "error": {"message": "training diverged"} if status == "failed" else None,
    }


def make_run_dir(
    distill_dir: Path,
    job_id: str,
    *,
    binds: Mapping[str, str],
    dataset_manifest_sha256: str,
    artifact_id: str = "a-0123456789ab",
    laya_version: str = "0.3.20",
    format_version: int = 1,
    status: str = "succeeded",
    training_file: str | None = None,
) -> Path:
    """runs/<job>/: the artifact (fixture files + manifest.json, §3.5) + SHA256SUMS over exactly
    those, plus job.json and events.jsonl, which are bookkeeping and not in SHA256SUMS or
    manifest.files."""
    run_dir = distill_dir / "runs" / job_id
    for rel in ARTIFACT_FILES:
        (run_dir / rel).parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(FIXTURE / rel, run_dir / rel)
    manifest = {
        "format_version": format_version,
        "artifact_id": artifact_id,
        "binds": {**binds, "dataset_manifest_sha256": dataset_manifest_sha256},
        "laya": {"version": laya_version, "commit": "23a1752"},
        "golden": {"n": len(golden_rows()), "tolerance": 0.001},
        "files": {rel: {"sha256": "", "size": 0} for rel in ARTIFACT_FILES},
    }
    _write_json(run_dir / MANIFEST, manifest)
    resum(run_dir)
    job = _job(
        job_id,
        status=status,
        model_id="laya-multilingual",
        training_file=training_file or "ds-" + dataset_manifest_sha256[:12],
        artifact_id=artifact_id,
    )
    _write_json(run_dir / "job.json", job)
    events = [
        {"object": "fine_tuning.job.event", "created_at": JOB_CREATED_AT, "level": "info",
         "message": "Validating training file"},
        {"object": "fine_tuning.job.event", "created_at": JOB_CREATED_AT + 600, "level": "info",
         "message": f"Job {status}"},
    ]
    (run_dir / "events.jsonl").write_text(
        "".join(json.dumps(event) + "\n" for event in events), encoding="utf-8"
    )
    return run_dir


def resum(directory: Path) -> None:
    """Rewrite manifest.files (if present) and SHA256SUMS over the artifact files after a test
    mutates one.

    The files are manifest.json plus every manifest.files key (for a dataset: the four .jsonl
    files). Each entry's ``sha256`` is recomputed, and so are ``size`` and ``rows`` where the
    entry has them (``splits.counts`` is left alone). Without a manifest ``files`` map, the
    paths already in SHA256SUMS are re-hashed.
    """
    manifest_path = directory / MANIFEST
    manifest = json.loads(manifest_path.read_text(encoding="utf-8")) if manifest_path.exists() else {}
    files = manifest.get("files")
    if isinstance(files, dict):
        for rel, entry in files.items():
            path = directory / rel
            entry["sha256"] = file_sha256(path)
            if "size" in entry:
                entry["size"] = path.stat().st_size
            if "rows" in entry:
                entry["rows"] = sum(1 for line in path.read_bytes().splitlines() if line.strip())
        _write_json(manifest_path, manifest)
        paths = [MANIFEST, *files]
    else:
        paths = list(parse_sha256sums((directory / SUMS_FILE).read_text(encoding="utf-8")))
    sums = {rel: file_sha256(directory / rel) for rel in paths}
    (directory / SUMS_FILE).write_text(format_sha256sums(sums), encoding="utf-8")
